
const welcome=document.getElementById("welcome"),invitation=document.getElementById("invitation"),enterBtn=document.getElementById("enterBtn"),musicBadge=document.getElementById("musicBadge"),musicBtn=document.getElementById("musicBtn"),musicIcon=document.getElementById("musicIcon"),bgMusic=document.getElementById("bgMusic");
document.body.style.overflow="hidden";
enterBtn.addEventListener("click",async()=>{try{bgMusic.volume=.55;await bgMusic.play();musicIcon.textContent="⏸"}catch(e){musicIcon.textContent="▶"}welcome.classList.add("hidden");invitation.classList.add("visible");invitation.setAttribute("aria-hidden","false");musicBadge.classList.add("visible");document.body.style.overflow="auto";setTimeout(()=>document.querySelector(".hero").classList.add("visible"),150)});
musicBtn.addEventListener("click",async()=>{if(bgMusic.paused){try{await bgMusic.play();musicIcon.textContent="⏸"}catch(e){}}else{bgMusic.pause();musicIcon.textContent="▶"}});
const weddingDate=new Date("2026-10-24T13:00:00+02:00");
function updateCountdown(){let diff=weddingDate.getTime()-Date.now();if(diff<=0){days.textContent=hours.textContent=minutes.textContent=seconds.textContent="0";countdownMessage.textContent="¡Ha llegado nuestro gran día!";return}days.textContent=Math.floor(diff/86400000);diff%=86400000;hours.textContent=String(Math.floor(diff/3600000)).padStart(2,"0");diff%=3600000;minutes.textContent=String(Math.floor(diff/60000)).padStart(2,"0");diff%=60000;seconds.textContent=String(Math.floor(diff/1000)).padStart(2,"0")}
updateCountdown();setInterval(updateCountdown,1000);
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")}),{threshold:.14});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
